- name: Kalliope Writer neuron install
  hosts: localhost
  gather_facts: no
  connection: local
  become: true

  tasks:
    - name: "Install pip dependencies"
      pip:
        name: python-libxdo
        version: 0.1.2a1